### ISSUE TITLE
Configuration for training baidu_V2 

### ISSUE THREAD

**Issue by ghost** [clovaai/ext_portrait_segmentation#1]
@HYOJINPARK Thank you for your hard work,

If I want to train baidu_V2, what exactly should I change?

Because I tried training baidu_V2 dataset, and got error:
```
FileNotFoundError: [Errno 2] No such file or directory: './baidu_V2//Portrait/train.txt'
```

So I placed the the files within  `Portrait` folder, like this:
```
baidu_V2
└── Portrait
    ├── input
    ├── target
    ├── train.txt
    └── val.txt
```

And now I am getting error:
```
ValueError: invalid literal for int() with base 10: '07517.jpg\n'
```

**Comment by HYOJINPARK** [comment]
In my case,
```
self.data_dir
└── Nukki
    └── baidu_V1
         ├── input
         ├── target
         ├── train.txt
         └── val.txt
   └── baidu_V2
         ├── input
         ├── target
         ├── train.txt
         └── val.txt
└── Portrait
```
this_additional is  " '/Nukki/baidu_V1/'" 

And code call additional dataset by
      img_file = ((self.data_dir).strip() + this_additoinal+'input/' + line.strip())
      label_file = ((self.data_dir).strip() + this_additoinal+'target/' + line.strip())

Finally
self.data_dir/Nukki/baidu_V1/input/ and self.data_dir/Nukki/baidu_V1/target/

The train.txt is also
self.data_dir/Nukki/baidu_V1/train.txt

Could you tell me your definition of additional_data variable???

**Comment by ghost** [comment]
@HYOJINPARK 

**I only want to train baidu_V1 & baidu_V2**, so from loadData.py I comment-out from line 57 to line 112.
see [loadData.py.zip](https://github.com/clovaai/ext_portrait_segmentation/files/4012792/loadData.py.zip)


SINet.json
```
"data_dir": "./dataset/",
```

Dataset folder tree
```
home@home-desktop:~/p10/ext_portrait_segmentation/dataset$ tree -L 3
.
├── Nukki
│   ├── baidu_V1
│   │   ├── input
│   │   ├── target
│   │   ├── train.txt
│   │   └── val.txt
│   └── baidu_V2
│       ├── input
│       ├── target
│       ├── train.txt
│       └── val.txt
└── Portrait
```

dataloader.py
```
additional_data = []
```

Now I am getting error:
see full log 
[log.txt](https://github.com/clovaai/ext_portrait_segmentation/files/4012799/log.txt)

```
Traceback (most recent call last):
  File "main.py", line 251, in <module>
    lossVal, ElossVal, mIOU_val = val_edge(num_gpu, valLoader, model, criteria, Lovasz)
  File "/home/home/p10/ext_portrait_segmentation/etc/help_function.py", line 25, in val_edge
    rand_pick = np.random.randint(0, len(val_loader))
  File "mtrand.pyx", line 992, in mtrand.RandomState.randint
ValueError: Range cannot be empty (low >= high) unless no samples are taken
```

**Comment by HYOJINPARK** [comment]
I am sorry for late answer for you.
These days, I leave from my home country for an internship in another country with a long trip.
Still, I need time more to set new experiment environment.
I will check your code this week.
Thanks for your waiting.

**Comment by ghost** [comment]
I understand, wishing you all the best.

**Comment by HYOJINPARK** [comment]
I think your problem of "rand_pick = np.random.randint(0, len(val_loader))" is that 
you don't use any validation dataset.
if you comment-out everything. 

If you want to train with Baidu dataset 
please just remove this 2 lines in loadData.py line  89, 90
```
self.trainImList.append(img_file)
self.trainAnnotList.append(label_file)
```
You can get this result
```
 Load public Baidu train dataset
This num of data is 10160
 Load public val dataset
This num of data is 270
```
Originally,
```
 Load public Baidu train dataset
This num of data is 11469
 Load public val dataset
This num of data is 270
```
This means that you train with only Baidu dataset and validate with EG1800 validation set
