### ISSUE TITLE
Pretrained model

### ISSUE THREAD

**Issue by ghost** [clovaai/ext_portrait_segmentation#2]
@HYOJINPARK Thank you

Upload a pretrained model so that we can test

**Comment by zhangyunming** [comment]
the pretrained  models in dir /result/..

**Comment by HYOJINPARK** [comment]
yes, the pre-trained file is in result folder

**Comment by ghost** [comment]
:sunglasses: the file was too small, I didnot notice it

**Comment by peace195** [comment]
Thanks for great work. The pretrained  model's results is not good as in the paper. Is it just a sample pretrained model for testing?

Thank you very much.

**Comment by HYOJINPARK** [comment]
Could you say more detailed information?

**Comment by peace195** [comment]
@HYOJINPARK I built a test service based on your pretrained model, the results is not good:
![image](https://user-images.githubusercontent.com/8999858/71812794-b2c43c80-30aa-11ea-9e07-c7db81b96a49.png)
![image](https://user-images.githubusercontent.com/8999858/71812798-b657c380-30aa-11ea-9fdb-4d2c40876d07.png)

**Comment by peace195** [comment]
![image](https://user-images.githubusercontent.com/8999858/71812835-c7083980-30aa-11ea-9d6e-8c440090dfb4.png)

**Comment by peace195** [comment]
@HYOJINPARK I tested with 
![image](https://user-images.githubusercontent.com/8999858/71874967-cc6e8e00-3155-11ea-90be-aa21dd75e687.png)
![image](https://user-images.githubusercontent.com/8999858/71874992-db554080-3155-11ea-999c-8470000c7b4d.png)

**Comment by HYOJINPARK** [comment]
Please check this code and result
![img1](https://user-images.githubusercontent.com/24826943/72033548-77ab4000-3247-11ea-8272-c2401a63d752.png)
![mask_img1](https://user-images.githubusercontent.com/24826943/72033550-7843d680-3247-11ea-89ac-14059f8b40a4.png)


[Test_image.py.zip](https://github.com/clovaai/ext_portrait_segmentation/files/4038351/Test_image.py.zip)

**Comment by GengCauWong** [comment]
> the pretrained models in dir /result/..

when I run Test_model.py to test the pretrained model，it occur errors.

  File "E:/test/ext_portrait_segmentation-master/Test_model.py", line 158, in <module>
    lossVal, ElossVal, mIOU_val = val_edge(num_gpu, valLoader, model, criteria, Lovasz)
  File "E:\test\ext_portrait_segmentation-master\etc\help_function.py", line 48, in val_edge
    epoch_loss.append(loss.item())
UnboundLocalError: local variable 'loss' referenced before assignment

Do you know how to solve it?

**Comment by ucb-pb** [comment]
The following block of code was indented incorrectly:

`with torch.no_grad():
            input_var, target_var, edge_target_var \
                = torch.autograd.Variable(input), torch.autograd.Variable(target), \
                    torch.autograd.Variable(edge_target)

            # run the mdoel
            output = model(input_var)

            # compute the loss
            loss = criterion(output, target_var)
            lossE = 0.5*criterion(output, edge_target_var)`

It should be at the same level as 
`if num_gpu > 0:`
Not inside that if statement.

**Comment by ucb-pb** [comment]
> > the pretrained models in dir /result/..
> 
> when I run Test_model.py to test the pretrained model，it occur errors.
> 
> File "E:/test/ext_portrait_segmentation-master/Test_model.py", line 158, in
> lossVal, ElossVal, mIOU_val = val_edge(num_gpu, valLoader, model, criteria, Lovasz)
> File "E:\test\ext_portrait_segmentation-master\etc\help_function.py", line 48, in val_edge
> epoch_loss.append(loss.item())
> UnboundLocalError: local variable 'loss' referenced before assignment
> 
> Do you know how to solve it?

The following block of code in help_function.py was indented incorrectly:

```
with torch.no_grad():
            input_var, target_var, edge_target_var \
                = torch.autograd.Variable(input), torch.autograd.Variable(target), \
                    torch.autograd.Variable(edge_target)

            # run the mdoel
            output = model(input_var)

            # compute the loss
            loss = criterion(output, target_var)
            lossE = 0.5*criterion(output, edge_target_var)
```

It should be at the same level as 
```
if num_gpu > 0:
            input = input.cuda()
            target = target.cuda()
            edge_target = edge_target.cuda()
```
Not inside that if statement.

**Comment by ucb-pb** [comment]
> Please check this code and result
> ![img1](https://user-images.githubusercontent.com/24826943/72033548-77ab4000-3247-11ea-8272-c2401a63d752.png)
> ![mask_img1](https://user-images.githubusercontent.com/24826943/72033550-7843d680-3247-11ea-89ac-14059f8b40a4.png)
> 
> [Test_image.py.zip](https://github.com/clovaai/ext_portrait_segmentation/files/4038351/Test_image.py.zip)

Thanks for this code

**Comment by shoutOutYangJie** [comment]
Great. Too Small .pth.
