### ISSUE TITLE
Rough edges in mask?

### ISSUE THREAD

**Issue by InternetMaster1** [clovaai/ext_portrait_segmentation#20]
@HYOJINPARK @yjyoo3312 

Thank you for the wonderful library! Wow!

I tried the demo on a sample image, but noticed that the edges on the output are rough. Can you guide me please..... 

This is for SINet

- Photo
![6d04664e-ad48-4e53-a281-bbd94e430147](https://user-images.githubusercontent.com/16253584/80521199-45fde680-89a8-11ea-84e4-07d3d684fdb8.jpg)

- Mask
![7c34da45-6ed7-4279-9a38-3cb035e98a21](https://user-images.githubusercontent.com/16253584/80521201-46967d00-89a8-11ea-8748-cb30794ebcc2.jpg)

- Composite
![a91298c3-0366-48b9-8369-0b5201ca2f1c](https://user-images.githubusercontent.com/16253584/80521198-44ccb980-89a8-11ea-85b0-d53ccf0bfeb4.jpg)

**Comment by InternetMaster1** [comment]
@ClovaAIAdmin @jeong 

1. Any help regarding rough edges?

2. I am looking to implement high-quality semantic segmentation on a mobile device for human cutout (full body).

What architecture/encoder would be a good choice for the task at hand? SINet or C3?

How does it compare with MobileNetV2, MobileNetV3, DeeplabV3+, ShuffleNet, PortraitNet, etc for segmentation task? There are so many models, its confusing which to select.

I am looking to get highly acccurate masks.

**Comment by HYOJINPARK** [comment]
1) how about a smooth filter for postprocessing?
2) I recommend SINet is better in mobile device

I compared with my model and others with EG1800 public dataset
PortraitNet I used official code and MobileNetV3 I reproduced by myself
I also think Deeblab and PortraitNet are accurate but too big for mobile device

**Comment by InternetMaster1** [comment]
Many thanks for the answer. 

Is there a chart comparing the accuracy, speed and parameters size of SINet with MobilenetV3, Deeplab, etc for segmentation?
