### ISSUE TITLE
Why is the label of eg1800 data set inconsistent with the number of images?

### ISSUE THREAD

**Issue by TCBocean** [clovaai/ext_portrait_segmentation#26]
The number of labels is 1887.
The number of pictures is 1630.

**Comment by qiutzh** [comment]
@TCBocean same doubt.

**Comment by TCBocean** [comment]
@qiutzh I read their paper, it is mentioned that some URLs are broken, so the whole data set is not obtained

**Comment by qiutzh** [comment]
@TCBocean Thanks!
